(()=>{
if(window.__swedsnusProductDataLoaded)return;
window.__swedsnusProductDataLoaded=true;
const DATA_URL='data/products.json';
const CART='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="9" cy="21" r="1"/><circle cx="20" cy="21" r="1"/><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"/></svg>';
const BOOK='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/></svg>';
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const st={rows:[],groups:new Map(),series:null,filters:{}};
const routes={
'portion.html':{title:'Alla portionsprodukter',f:r=>r.product_family==='Portionssnus'&&r.site_section==='Portionssnus'&&r.tobacco_type!=='Tobaksfri',p:[['white','White Portion','Färdigt portionssnus'],['instant','Instant Portion','Färdig att snusa'],['superdry','Super Dry','Osmaksatt bas']]},
'los.html':{title:'Alla lössnusprodukter',f:r=>r.site_section==='Lössnus'||r.aroma_type==='Expressarom',p:[['instant','Instant','Färdig att snusa'],['express','Express','Snussats'],['aromer','Expressaromer','Smaksättning']]},
'gor-eget.html':{title:'Alla produkter för Gör Eget',f:r=>r.site_section==='Gör eget'||r.aroma_type==='Super Dry Arom',p:[['instant','Instant Portion','Färdig att snusa'],['superdry','Super Dry','Osmaksatt bas'],['aromer','Super Dry Aromer','Smaksättning']]},
'vitt-snus.html':{title:'Alla tobaksfria produkter',f:r=>r.tobacco_type==='Tobaksfri'||r.site_section==='Vitt snus',p:[['rebell','Rebell','Tobaksfri portion'],['rx-slim','RX Slim','Tobaksfri slim'],['compact-mini','Compact & Mini','Tobaksfria mindre format']]},
'tillbehor.html':{title:'Alla tillbehör',f:r=>r.product_family==='Tillbehör',p:[['portion','Portionssnus','Tillbehör till portionssnus'],['lossnus','Lössnus','Tillbehör till lössnus'],['general','Övrigt','Övriga tillbehör']]}
};
const dynamicProductPages=new Set(['product-portion.html','product-los.html']);
const pg=()=>location.pathname.split('/').pop()||'index.html';
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const slug=v=>String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')||'produkt';
const split=v=>String(v||'').split(',').map(x=>x.trim()).filter(Boolean);
const uniq=a=>[...new Set(a.filter(v=>v!==null&&v!==undefined&&v!=='').map(v=>String(v).trim()))];
const visible=r=>r.product_id&&String(r.visible_on_site||'Yes').toLowerCase()!=='no';
const price=r=>r.price_sek?`${Number(r.price_sek).toLocaleString('sv-SE')} kr`:'';
const amount=r=>r.amount_dosor?`${r.amount_dosor} dosor`:r.package_quantity?`${r.package_quantity}-pack`:'1-pack';
const name=r=>r.generated_name||[r.taste_name,r.product_line,r.strength!=='Normal'?r.strength:'',r.format,r.grind&&r.grind!=='Standard'?r.grind:'',r.amount_dosor?`${r.amount_dosor} dosor`:''].filter(Boolean).join(' ');
const rowKey=r=>`${r.product_id}__${r.variant_id||r.sku_draft||slug(name(r))}`;
function dec(v,d){if(v==='')return null;if(String(v).startsWith('~'))return d[Number(String(v).slice(1))]??null;const x=decodeURIComponent(String(v));return/^-?\d+(\.\d+)?$/.test(x)?Number(x):x}
function expand(data){if(Array.isArray(data))return data;if(Array.isArray(data?.headers)&&Array.isArray(data?.rows))return data.rows.map(r=>Object.fromEntries(data.headers.map((h,i)=>[h,r[i]??null])));if(Array.isArray(data?.cols)&&typeof data.rows==='string')return data.rows.split('\n').filter(Boolean).map(line=>{const a=line.split('|');return Object.fromEntries(data.cols.map((h,i)=>[h,dec(a[i]??'',data.dict||[])]))});return[]}
function groupRows(rows){const groups=new Map;rows.filter(visible).forEach(row=>{if(!groups.has(row.product_id))groups.set(row.product_id,[]);groups.get(row.product_id).push(row)});return groups}
function series(row){const line=String(row.product_line||'').toLowerCase(),family=String(row.product_family||'').toLowerCase(),aroma=String(row.aroma_type||'').toLowerCase(),format=slug(row.format||''),text=slug(`${row.generated_name||''} ${row.accessory_type||''}`);if(row.tobacco_type==='Tobaksfri')return format==='rx-slim'?'rx-slim':['compact','mini'].includes(format)?'compact-mini':format||'rebell';if(family==='aromer'||aroma.includes('arom'))return'aromer';if(line.includes('super dry'))return'superdry';if(line.includes('instant'))return'instant';if(line.includes('express'))return'express';if(line.includes('white'))return'white';if(family==='tillbehör'||family==='tillbehor')return text.includes('los')||text.includes('lossnus')?'lossnus':text.includes('portion')?'portion':'general';return'product'}
function pageFor(row){if(row.product_family==='Lössnus')return'product-los.html';if(row.product_family==='Aromer')return'product-arom.html';if(row.product_family==='Tillbehör')return'product-tillbehor.html';return'product-portion.html'}
function urlFor(row){return`${pageFor(row)}?id=${encodeURIComponent(rowKey(row))}`}
function dots(row){if(!row.strength||row.product_family==='Aromer'||row.product_family==='Tillbehör')return'';const level=row.strength==='Extra Strong'?4:row.strength==='Strong'?3:2;return`<div class="strength-bar">${[1,2,3,4].map(i=>`<span${i<=level?' class="filled"':''}></span>`).join('')}</div>`}
function meta(row){return[['Typ',row.product_line||row.aroma_type||row.accessory_type],['Smak',row.taste_display],['Format',row.format],['Malningsgrad',row.grind],['Tobak',row.tobacco_type==='Tobaksfri'?'Tobaksfri':'']].filter(x=>x[1]).slice(0,3).map(([label,value])=>`<p class="product-card-meta">${esc(label)}: <span>${esc(value)}</span></p>`).join('')}
function card(row){return`<div class="product-card" data-product-source="json" data-experience-enhanced="true" data-product-id="${esc(rowKey(row))}" data-product-group="${esc(row.product_id)}" data-variant-id="${esc(row.variant_id||'')}" data-series="${esc(series(row))}" data-taste="${esc(split(row.taste_variables).join('|'))}" data-type="${esc(row.product_line||row.aroma_type||row.accessory_type||'')}" data-format="${esc(row.format||row.grind||row.aroma_type||row.accessory_type||'')}" data-strength="${esc(row.strength||'')}" data-amount="${esc(amount(row))}" data-href="${esc(urlFor(row))}"><button class="bookmark-toggle requires-login" data-product-id="${esc(rowKey(row))}" type="button" aria-label="Spara produkt" aria-pressed="false">${BOOK}</button><div class="img-placeholder product">Produktbild</div><div class="product-card-body"><span class="product-card-badge">${esc(row.format||row.product_line||row.aroma_type||row.accessory_type||'Produkt')}</span><p class="product-card-name">${esc(name(row))}</p>${meta(row)}${dots(row)}<div class="product-card-actions"><select class="pack-select" aria-label="Välj antal"><option data-price="${esc(price(row))}" data-pack="1-pack">1-pack — ${esc(price(row))}</option></select></div><div class="product-card-bottom"><p class="product-card-price"><span class="unit-price">${esc(price(row))}</span><small>per produkt</small></p><button class="add-to-cart-btn" type="button" aria-label="Lägg i kundvagn">${CART}</button></div></div></div>`}
function filterGroup(title,key,values){return values.length?`<div class="sidebar-group" data-filter-group="${esc(key)}"><h4>${esc(title)}</h4>${values.map(value=>`<label class="sidebar-check"><input type="checkbox" value="${esc(value)}" />${esc(value)}</label>`).join('')}</div>`:''}
function buildSidebar(rows){const values={taste:[],type:[],format:[],strength:[],amount:[]};rows.forEach(row=>{values.taste.push(...split(row.taste_variables));values.type.push(row.product_line||row.aroma_type||row.accessory_type);values.format.push(row.format||row.grind||row.aroma_type||row.accessory_type);values.strength.push(row.strength);values.amount.push(amount(row))});const sidebar=$('.filter-sidebar');if(sidebar)sidebar.innerHTML=filterGroup('Smak','taste',uniq(values.taste).sort())+filterGroup('Typ','type',uniq(values.type).sort())+filterGroup('Format','format',uniq(values.format).sort())+filterGroup('Styrka','strength',uniq(values.strength).sort())+filterGroup('Mängd','amount',uniq(values.amount).sort())}
function applyFilters(){const cards=$$('.catalog-page .product-card'),count=$('.catalog-count'),empty=$('.catalog-empty');let visibleCount=0;cards.forEach(card=>{const ok=(!st.series||card.dataset.series===st.series)&&Object.entries(st.filters).every(([key,set])=>!set.size||(key==='taste'?[...set].some(x=>(card.dataset[key]||'').split('|').includes(x)):set.has(card.dataset[key]||'')));card.classList.toggle('is-hidden',!ok);if(ok)visibleCount++});if(count)count.textContent=`${visibleCount} ${visibleCount===1?'produkt':'produkter'}`;if(empty)empty.classList.toggle('show',visibleCount===0)}
function bindFilters(){$$('.filter-pill[data-series]').forEach(button=>button.addEventListener('click',()=>{st.series=st.series===button.dataset.series?null:button.dataset.series;$$('.filter-pill[data-series]').forEach(item=>item.classList.toggle('active',st.series===item.dataset.series));applyFilters()}));$$('.filter-sidebar [data-filter-group]').forEach(group=>{const key=group.dataset.filterGroup;st.filters[key]=new Set;$$('input',group).forEach(input=>input.addEventListener('change',()=>{st.filters[key]=new Set($$('input:checked',group).map(item=>item.value));applyFilters()}))})}
function renderCatalog(){const route=routes[pg()],grid=$('.catalog-page .product-grid');if(!route||!grid)return;const rows=st.rows.filter(row=>visible(row)&&route.f(row));const pills=$('.category-pills');if(pills)pills.innerHTML=route.p.map(([value,title,subtitle])=>`<button class="filter-pill" data-series="${esc(value)}" type="button"><span class="filter-pill-icon"></span><span class="filter-pill-copy"><span class="filter-pill-title">${esc(title)}</span><span class="filter-pill-subtitle">${esc(subtitle)}</span></span><span class="filter-pill-close">×</span></button>`).join('');buildSidebar(rows);grid.innerHTML=rows.map(card).join('');const header=$('.catalog-results-header span:first-child');if(header)header.innerHTML=`<strong>${esc(route.title)}</strong>`;st.series=null;st.filters={};bindFilters();applyFilters()}
function fields(row){if(row.product_family==='Lössnus')return[['amount','Mängd'],['grind','Malningsgrad'],['strength','Styrka']];return[['format','Format'],['amount','Portioner'],['strength','Styrka']]}
function value(row,field){return field==='amount'?amount(row):row[field]||''}
function currentRow(){const q=new URLSearchParams(location.search),id=q.get('id'),product=q.get('product'),variant=q.get('variant');if(id){const found=st.rows.find(row=>rowKey(row)===id);if(found)return found}if(product&&variant){const found=st.rows.find(row=>row.product_id===product&&String(row.variant_id||'')===variant);if(found)return found}if(product){const found=st.rows.find(row=>row.product_id===product);if(found)return found}const fallback=pg()==='product-los.html'?row=>row.product_family==='Lössnus':row=>row.product_family==='Portionssnus';return st.rows.find(row=>visible(row)&&fallback(row))}
function rowSpecs(row){return[['Produktlinje',row.product_line],['Tobakstyp',row.tobacco_type&&row.tobacco_type!=='Ej tillämpligt'?row.tobacco_type:''],['Format',[row.format,row.format_dimensions].filter(Boolean).join(', ')],['Fyllnad',row.fill_level],['Smak',row.taste_display],['Malningsgrad',row.grind],['Styrka',[row.strength,row.strength_mg_g].filter(Boolean).join(', ')],['Nikotinhalt',row.nicotine_per_portion],['Förpackningsstorlek',row.portions_total?`${row.amount_dosor} dosor (${row.portions_total} portioner)`:row.amount_dosor?amount(row):''],['Hållbarhet',row.shelf_life],['Tillverkningsort',row.manufacturing_location]]}
function renderDetail(row){const detail=$('.product-detail');if(!detail||!row)return;detail.dataset.productId=rowKey(row);const title=$('[data-product-title]',detail)||$('h1',detail);if(title)title.textContent=name(row);document.title=`${name(row)} — Swedsnus`;const breadcrumb=$('[data-product-breadcrumb]');if(breadcrumb)breadcrumb.textContent=name(row);const badge=$('.product-detail-badge',detail);if(badge)badge.innerHTML=`<span class="product-card-badge">${esc(row.format||row.product_line||row.product_family)}</span>${row.tobacco_type==='Tobaksfri'?'<span class="product-card-badge" style="background:var(--color-accent);">Tobaksfri</span>':''}`;const priceEl=$('.product-detail-price',detail);if(priceEl)priceEl.innerHTML=`${esc(price(row))} <small>1-pack</small>`;const desc=$('.product-desc',detail);if(desc)desc.textContent=row.short_description||`${name(row)} visas från produktdatan.`;const metaRows=[['Typ',row.product_line||row.product_family],['Smak',row.taste_display],['Format',row.format],['Malningsgrad',row.grind],['Styrka',row.strength],['Tobak',row.tobacco_type==='Tobaksfri'?'Tobaksfri':''],['Tillverkning',row.manufacturing_location]];const metaEl=$('.product-detail-meta',detail);if(metaEl)metaEl.innerHTML=metaRows.filter(item=>item[1]).slice(0,5).map(([label,val])=>`<div class="product-detail-meta-row"><dt>${esc(label)}</dt><dd>${esc(val)}</dd></div>`).join('');const spec=$('.product-spec-table tbody',detail);if(spec)spec.innerHTML=rowSpecs(row).filter(item=>item[1]).map(([label,val])=>`<tr><td>${esc(label)}</td><td>${esc(val)}</td></tr>`).join('');const pack=$('.pack-picker-options',detail);if(pack)pack.innerHTML=`<label class="pack-option selected" data-price="${esc(price(row))}" data-pack="1-pack"><input type="radio" name="pack" value="1" checked /><span class="pack-option-label">1-pack</span><span class="pack-option-price">${esc(price(row))}</span><span class="pack-option-per">${esc(price(row))}/st</span></label>`;$$('.bookmark-toggle',detail).forEach(button=>button.dataset.productId=rowKey(row))}
function matchingVariant(group,selected,changed,current){const exact=group.find(row=>Object.entries(selected).every(([field,val])=>!val||value(row,field)===val));if(exact)return exact;if(changed&&selected[changed]){const changedOnly=group.find(row=>value(row,changed)===selected[changed]);if(changedOnly)return changedOnly}return current}
function renderProductPage(){if(!dynamicProductPages.has(pg()))return;const row=currentRow();if(!row)return;const group=st.groups.get(row.product_id)||[row];const detail=$('.product-detail');if(!detail)return;const productFields=fields(row).filter(([field])=>uniq(group.map(item=>value(item,field))).length>0);let panel=$('.product-choice-panel',detail);if(productFields.length){if(!panel){panel=document.createElement('section');panel.className='product-choice-panel';$('.pack-picker-label',detail)?.insertAdjacentElement('beforebegin',panel)}panel.innerHTML=`<p class="product-choice-panel-title">Produktval</p><div class="product-choice-grid">${productFields.map(([field,label])=>`<div class="product-choice-field"><label>${esc(label)}</label><select data-data-field="${esc(field)}">${uniq(group.map(item=>value(item,field))).map(option=>`<option${option===value(row,field)?' selected':''}>${esc(option)}</option>`).join('')}</select></div>`).join('')}</div>`;productFields.forEach(([field])=>{const select=$(`[data-data-field="${field}"]`,panel);if(!select)return;select.addEventListener('change',()=>{const selected=Object.fromEntries(productFields.map(([itemField])=>[itemField,$(`[data-data-field="${itemField}"]`,panel)?.value||'']));const target=matchingVariant(group,selected,field,row);if(rowKey(target)!==rowKey(row))location.href=urlFor(target)})})}else if(panel){panel.remove()}renderDetail(row)}
function renderIndex(){if(pg()!=='index.html')return;const rows=st.rows.filter(visible);const track=$('.carousel-track');if(track)track.innerHTML=rows.slice(0,12).map(card).join('');const showcase=$('.vitt-showcase-track');if(showcase)showcase.innerHTML=rows.filter(row=>row.tobacco_type==='Tobaksfri').slice(0,6).map(card).join('')}
async function init(){try{const response=await fetch(DATA_URL,{cache:'no-cache'});st.rows=expand(await response.json()).filter(visible);st.groups=groupRows(st.rows);window.SwedsnusProducts={rows:st.rows,groups:st.groups,rowKey,urlFor};renderCatalog();renderProductPage();renderIndex();document.dispatchEvent(new CustomEvent('swedsnus:products-rendered'))}catch(error){document.documentElement.classList.add('product-data-load-failed');console.error(error)}}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
